package com.rclgroup.dolphin.utils;

public interface DBConstants {

	// COMMONS ORACLE Variables used in Application

	String P_I_LINE = "P_I_LINE";
	String P_I_TRADE = "P_I_TRADE";
	String P_I_AGENT = "P_I_AGENT";
	String P_I_FSC = "P_I_FSC";
	String P_I_USER_ID = "P_I_USER_ID";
	String P_I_SERVICE = "P_I_SERVICE";
	String P_I_VESSEL = "P_I_VESSEL";
	String P_I_VOYAGE = "P_I_VOYAGE";
	String P_I_POD = "P_I_POD";
	String P_I_POL_TERMINAL = "P_I_POL_TERMINAL";
	String P_I_POD_TERMINAL = "P_I_POD_TERMINAL";
	String P_I_ETA_FROM_DATE = "P_I_ETA_FROM_DATE";
	String P_I_ETA_TO_DATE = "P_I_ETA_TO_DATE";
	String P_I_SOC_COC = "P_I_SOC_COC";
	String P_I_FILTER_BY = "P_I_FILTER_BY";
	String P_I_PORT_TERMINAL = "P_I_PORT_TERMINAL";
	
	String P_I_ETA = "P_I_ETA";
	String P_I_DIRECTION = "P_I_DIRECTION";
	String P_I_BL_NO = "P_I_BL_NO";
	String P_I_DATE_FROM = "P_I_DATE_FROM";
	String P_I_DATE_TO = "P_I_DATE_TO";
	String P_I_FROM_DATE = "P_I_FROM_DATE";
	String P_I_TO_DATE = "P_I_TO_DATE";
	String P_I_PORT = "P_I_PORT";
	String P_I_IMPORT_EXPORT = "P_I_IMPORT_EXPORT";
	String P_I_ETA_ATA = "P_I_ETA_ATA";
	String P_I_POL = "P_I_POL";
	String P_I_BOOKING_NO = "P_I_BOOKING_NO";
	String P_I_SESSION_ID = "P_I_SESSION_ID";
	String P_I_FROM_LOCATION = "P_I_FROM_LOCATION";
	String P_I_TO_LOCATION = "P_I_TO_LOCATION";
	String P_I_MODE_TRANSPORT = "P_I_MODE_TRANSPORT";
	String P_I_VALID_DATE = "P_I_VALID_DATE";
	String P_I_RATE_TY = "P_I_RATE_TY";
	String P_I_JOB_ORDER_NO = "P_I_JOB_ORDER_NO";
	String P_I_IPV_FROM_DATE = "P_I_IPV_FROM_DATE";
	String P_I_IPV_TO_DATE = "P_I_IPV_TO_DATE";
	String P_I_TERMINAL = "P_I_TERMINAL";
	String P_I_MODULE = "P_I_MODULE";
	String P_I_VENDOR_CODE = "P_I_VENDOR_CODE";
	
	// TOS Package Name
	String PCR_JASPER_TOS_T1 = "RCLAPPS.PCR_JASPER_REPORT_TOS_T1";
	String PCR_JASPER_TOS_T2 = "RCLAPPS.PCR_JASPER_REPORT_TOS_T2";//PCR_JASPER_REPORT_TOS_T2
	String PCR_JASPER_TOS_T3 = "RCLAPPS.PCR_JASPER_REPORT_TOS_T3";//PCR_JASPER_REPORT_TOS_T3
	String PCR_JASPER_TOS_T4 = "RCLAPPS.PCR_JASPER_REPORT_TOS_T4";//PCR_JASPER_REPORT_TOS_T4
	
	// TOS Procedure Name
	String PRR_GET_TOS101 = "PRR_GET_TOS101";
	String PRR_GET_TOS102 = "PRR_GET_TOS102";
	String PRR_GET_TOS102_RSE_DETAIL = "PRR_GET_TOS102_RSE_DETAIL";
	String PRR_GET_TOS105_DETAIL = "PRR_GET_TOS105_DETAIL";
	String PRR_GET_TOS105_EXCEL_DETAIL = "PRR_GET_TOS105_EXCEL_DETAIL";
	String PRR_GET_TOS106_DETAIL_LIST  = "PRR_GET_TOS106_DETAIL_LIST";
	String PRR_GET_TOS106_DETAIL_EXCEL = "PRR_GET_TOS106_DETAIL_EXCEL";
	String PRR_GET_TOS106_SUMMARY_LIST = "PRR_GET_TOS106_SUMMARY_LIST";
	String PRR_GET_TOS106_SUMMARY_EXCEL = "PRR_GET_TOS106_SUMMARY_EXCEL";
	String PRR_GET_TOS108_DETAIL = "PRR_GET_TOS108_DETAIL";
	String PRR_GET_TOS108_SUMMARY = "PRR_GET_TOS108_SUMMARY";
	String PRR_GET_TOS110 = "PRR_GET_TOS110";
	String PRR_GET_TOS111 = "PRR_GET_TOS111";
	String PRR_GET_TOS112 = "PRR_GET_TOS112";
	String PRR_GET_TOS_115_LOAD_LIST = "PRR_GET_TOS_115_LOAD_LIST";
	String PRR_GET_TOS_115_LOAD_LIST_EXCEL  = "PRR_GET_TOS_115_LOAD_LIST_EXCEL ";
	String PRR_GET_TOS116_DETAIL = "PRR_GET_TOS116_DETAIL";
	String PRR_GET_TOS116_EXCEL_DETAIL = "PRR_GET_TOS116_EXCEL_DETAIL";
	String PRR_GET_TOS117 = "PRR_GET_TOS117";
	String PRR_GET_TOS117_EXCEL_DETAIL = "PRR_GET_TOS117_EXCEL_DETAIL";
	String PRR_GET_TOS118_01_SHS_EXCEL = "PRR_GET_TOS118_01_SHS_EXCEL";
	String PRR_GET_TOS118_01_SHS = "PRR_GET_TOS118_01_SHS";
	String PRR_GET_TOS118_02_EXCEL_DETAIL = "PRR_GET_TOS118_02_EXCEL_DETAIL";
	String PRR_GET_TOS118_02_LIST = "PRR_GET_TOS118_02_LIST";
	String PRR_GET_TOS120 = "PRR_GET_TOS120";
	String PRR_GET_TOS120_EXCEL = "PRR_GET_TOS120_EXCEL";
	String PRR_GET_TOS121_DISCH_EXCEL_DETAIL = "PRR_GET_TOS121_DISCH_EXCEL_DETAIL";
	String PRR_GET_TOS121_LOAD_EXCEL_DETAIL = "PRR_GET_TOS121_LOAD_EXCEL_DETAIL";
	String PRR_GET_TOS122_EXCEL_LIST = "PRR_GET_TOS122_EXCEL_LIST";
	String PRR_GET_TOS_124_RSE = "PRR_GET_TOS_124_RSE";
	String PRR_GET_TOS_124_EXCEL_RSE = "PRR_GET_TOS_124_EXCEL_RSE";
	String PRR_GET_TOS114  = "PRR_GET_TOS114";
	String PRR_GET_TOS114_EXCEL   = "PRR_GET_TOS114_EXCEL";
	String PRR_GET_TOS130_RSE_EXCEL = "PRR_GET_TOS130_RSE_EXCEL";
	String PRR_GET_TOS131_RSE_EXCEL = "PRR_GET_TOS131_RSE_EXCEL";
	String PRR_GET_TOS_109_ALL = "PRR_GET_TOS_109_ALL";
	String PRR_GET_TOS_109_ALL_EXCEL = "PRR_GET_TOS_109_ALL_EXCEL";
	String PRR_GET_TOS_109_ERROR = "PRR_GET_TOS_109_ERROR";
	String PRR_GET_TOS_109_ERROR_EXCEL = "PRR_GET_TOS_109_ERROR_EXCEL";
	String PRR_GET_TOS101_RSE_EXCEL = "PRR_GET_TOS101_RSE_EXCEL";
	String PRR_GET_TOS101_RSE= "PRR_GET_TOS101_RSE";
	String PRR_GET_TOS105_RSE_EXCEL = "PRR_GET_TOS105_RSE_EXCEL";    

	// IJS Package name
	String PCR_JASPER_IJS = "RCLAPPS.PCR_JASPER_REPORT_IJS";

	// IJS Procedure name
	String PRR_GET_IJS101_DETAIL = "PRR_GET_IJS101_DETAIL";
	String PRR_GET_IJS103_DETAIL = "PRR_GET_IJS103_DETAIL";
	String PRR_GET_IJS104_DETAIL = "PRR_GET_IJS104_DETAIL";

	// IPV Package name
	String PCR_JASPER_IPV = "RCLAPPS.PCR_JASPER_REPORT_IPV";
	
	// IPV Procedure name
	String PRR_GET_IPV103_PO = "PRR_GET_IPV103_PO";
	String PRR_GET_IPV103_PO_EXCEL  = "PRR_GET_IPV103_PO_EXCEL";
	String PRR_GET_IPV101_RSE_EXCEL = "PRR_GET_IPV101_RSE_EXCEL";
	String PRR_GET_IPV101_RSE = "PRR_GET_IPV101_RSE";
	
	// MNR Package name
	String PCR_JASPER_MNR = "RCLAPPS.PCR_JASPER_REPORT_MNR";
	
	// MNR Procedure name
	String PRR_GET_MNR101_DETAIL = "PRR_GET_MNR101_DETAIL";
	String PRR_GET_MNR102_DETAIL = "PRR_GET_MNR102_DETAIL";
	
	// STR Package name
	String PCR_JASPER_STR = "RCLAPPS.PCR_JASPER_REPORT_STR";
	
	// MNR Procedure name
	String PRR_GET_STR113_RSE_EXCEL = "PRR_GET_STR113_RSE_EXCEL";
	String PRR_GET_STR119_RSE_EXCEL_NEW_1 = "PRR_GET_STR119_RSE_EXCEL_NEW_1";
	String PRR_GET_STR119_RSE_PDF = "PRR_GET_STR119_RSE_PDF";
	String PRR_GET_STR116_RSE_EXCEL = "PRR_GET_STR116_RSE_EXCEL";
	String PRR_GET_STR117_RSE_EXCEL = "PRR_GET_STR117_RSE_EXCEL";
	String PRR_GET_STR118_RSE_EXCEL = "PRR_GET_STR118_RSE_EXCEL";
	String PRR_GET_STR115_RSE_EXCEL = "PRR_GET_STR115_RSE_EXCEL";
	String PRR_GET_STR112_RSE_EXCEL = "PRR_GET_STR112_RSE_EXCEL";
	
	// MNR Package name
	String PCR_JASPER_SYS = "RCLAPPS.PCR_JASPER_REPORT_SYS";

	// MNR Procedure name
	String PRR_GET_SYS105_DETAIL = "PRR_GET_SYS105_DETAIL";
	
	// VMS Package name
	String PCR_JASPER_VMS = "RCLAPPS.PCR_JASPER_REPORT_VMS";
	String PCR_JASPER_VMS_V2  = "RCLAPPS.PCR_JASPER_REPORT_VMS_V2";
	
	// VMS Procedure name
	String PRR_GET_VMS101_SOC= "PRR_GET_VMS101_SOC";
	String PRR_GET_VMS101_SOC_EXCEL= "PRR_GET_VMS101_SOC_EXCEL";
	String PRR_GET_VMS101_COC = "PRR_GET_VMS101_COC";
	String PRR_GET_VMS101_COC_EXCEL = "PRR_GET_VMS101_COC_EXCEL";       
	String PRR_GET_VMS101_RSE = "PRR_GET_VMS101_RSE";
	String PRR_GET_VMS102_LIST = "PRR_GET_VMS102_LIST";
	String PRR_GET_VMS102_EXCEL = "PRR_GET_VMS102_EXCEL";
	String PRR_GET_VMS107_PERIOD = "PRR_GET_VMS107_PERIOD";
	String PRR_GET_VMS107_PERIOD_EXCEL  = "PRR_GET_VMS107_PERIOD_EXCEL";
	String PRR_GET_VMS107_VOYAGE_EXCEL  = "PRR_GET_VMS107_VOYAGE_EXCEL";
	String PRR_GET_VMS107_VOYAGE  = "PRR_GET_VMS107_VOYAGE";
	String PRR_GET_VMS108_AGC_DTL = "PRR_GET_VMS108_AGC_DTL";
	String PRR_GET_VMS108_AGC_SUM = "PRR_GET_VMS108_AGC_SUM";
	String PRR_GET_VMS108_FRT_DTL = "PRR_GET_VMS108_FRT_DTL";
	String PRR_GET_VMS108_FRT_SUM = "PRR_GET_VMS108_FRT_SUM";
	String PRR_GET_VMS108_FRT_DTL_EXCEL = "PRR_GET_VMS108_FRT_DTL_EXCEL";
	String PRR_GET_VMS108_FRT_SUM_EXCEL = "PRR_GET_VMS108_FRT_SUM_EXCEL";
	String PRR_GET_VMS108_AGC_DTL_EXCEL = "PRR_GET_VMS108_AGC_DTL_EXCEL";
	String PRR_GET_VMS108_AGC_SUM_EXCEL = "PRR_GET_VMS108_AGC_SUM_EXCEL";
	
	String ZERO_STR = "0";
	String ONE_STR = "1";
	String FALSE = "FALSE";
	String TRUE = "TRUE";
	String HTTP_500 = "500";
	String FAILED = "FAILED";
	String SUCCESS = "SUCCESS";
	
	String P_I_DEPOT_CODE = "P_I_DEPOT_CODE";
	String P_I_EOR_STATUS = "P_I_EOR_STATUS";
	String P_I_EQUIP_I_NO = "P_I_EQUIP_I_NO";
	String P_I_NEXT_PORT = "P_I_NEXT_PORT";
	String P_I_EQ_NO = "P_I_EQ_NO";
	String P_I_FROM = "P_I_FROM";
	String P_I_TO = "P_I_TO";
	String P_I_COMPLETE_FROM = "P_I_COMPLETE_FROM";
	String P_I_COMPLETE_TO = "P_I_COMPLETE_TO";
	String P_I_ORG_CODE = "P_I_ORG_CODE";
	String P_I_READ_ONLY = "P_I_READ_ONLY";
	String P_I_CURRENCY = "P_I_CURRENCY";
	String P_I_EOR_NO = "P_I_EOR_NO";
	String P_I_POINT_CODE = "P_I_POINT_CODE";
	String P_I_EQUIP_NO = "P_I_EQUIP_NO";
	String P_I_FSC_CODE = "P_I_FSC_CODE";
	String P_I_SIZE = "P_I_SIZE";
	String P_I_STATUS = "P_I_STATUS";
	String P_I_TYPE = "P_I_TYPE";
	String P_I_CREATE_FROM = "P_I_CREATE_FROM";
	String P_I_CREATE_TO = "P_I_CREATE_TO";
	String P_I_APPROVE_FROM = "P_I_APPROVE_FROM";
	String P_I_APPROVE_TO = "P_I_APPROVE_TO";
	String P_I_GATEIN_FROM = "P_I_GATEIN_FROM";
	String P_I_GATEIN_TO = "P_I_GATEIN_TO";
	String P_I_INSTR_FROM = "P_I_INSTR_FROM";
	String P_I_INSTR_TO = "P_I_INSTR_TO";
	String P_I_DEPOT = "P_I_DEPOT";
	String P_I_COUNTRY = "P_I_COUNTRY";
	String P_I_AGREEMENT_NO = "P_I_AGREEMENT_NO";
	String P_I_POINT = "P_I_POINT";
	String P_I_VENDOR = "P_I_VENDOR";
	String P_I_EXCL_EXPIRE = "P_I_EXCL_EXPIRE";
	String P_I_USER_LOGIN_FSC = "P_I_USER_LOGIN_FSC";
	String P_I_AGREEMENT = "P_I_AGREEMENT";
	String P_I_EMPTY_LADEN = "P_I_EMPTY_LADEN";
	String P_I_PROFORMA_NO = "P_I_PROFORMA_NO";
	String P_I_PROF_STATUS = "P_I_PROF_STATUS";
	String P_I_CHARGE_CODE = "P_I_CHARGE_CODE";
	String P_I_REPORT_MOD = "P_I_REPORT_MOD";
	String P_I_PERIOD_FROM = "P_I_PERIOD_FROM";
	String P_I_PERIOD_TO = "P_I_PERIOD_TO";
	String P_I_ETD_FROM = "P_I_ETD_FROM";
	String P_I_ETD_TO = "P_I_ETD_TO";
	String P_I_CR_PERIOD_FR = "P_I_CR_PERIOD_FR";
	String P_I_CR_PERIOD_TO = "P_I_CR_PERIOD_TO";
	String P_I_LOCATION = "P_I_LOCATION";
	String P_I_USER_LOGIN_ID = "P_I_USER_LOGIN_ID";
	String P_I_PROF_NO = "P_I_PROF_NO";
	String P_I_COC_SOC = "P_I_COC_SOC";
	String P_I_EXPORT_IMPORT = "P_I_EXPORT_IMPORT";
	
	String P_I_USER_NAME = "P_I_USER_NAME";
	String P_I_LIST_STATUS_BY = "P_I_LIST_STATUS_BY";
	String P_I_USR_PERM = "P_I_USR_PERM";
	String P_I_OPERATOR_CODE = "P_I_OPERATOR_CODE";
	String P_I_OPERATOR = "P_I_OPERATOR";
	String P_I_CONTAINER_TYPE = "P_I_CONTAINER_TYPE";
	String P_I_INV_FR = "P_I_INV_FR";
	String P_I_INV_TO = "P_I_INV_TO";
	String P_I_INB_OUB = "P_I_INB_OUB";
	String P_I_LOCAL_TRANSHIPMENT = "P_I_LOCAL_TRANSHIPMENT";
	String P_I_FULL_EMPTY = "P_I_FULL_EMPTY";
	String P_I_SELECT_BY = "P_I_SELECT_BY";
	String P_I_USER = "P_I_USER";
	String P_I_DIRECT = "P_I_DIRECT";
	String P_I_PROFORMA_REF_NO = "P_I_PROFORMA_REF_NO";
	String P_I_SERVICE_CODE = "P_I_SERVICE_CODE";
	String P_I_PORT_CODE = "P_I_PORT_CODE";
	String P_I_COUNTRY_CODE = "P_I_COUNTRY_CODE";
	String P_I_PORT_SEQ="P_I_PORT_SEQ";
	String P_I_DG="P_I_DG";
	String P_I_SLOT_OPR_Code="P_I_SLOT_OPR_Code";
	String P_I_SLOT_OPR="P_I_SLOT_OPR";
	String P_I_LOADING_TYPE="P_I_LOADING_TYPE";
	String P_I_EQT="P_I_EQT";
	String P_I_ETD="P_I_ETD";
	String P_I_EX_VESSEL="P_I_EX_VESSEL";
	String P_I_EX_VOYAGE="P_I_EX_VOYAGE";
	String P_I_USER_FSC="P_I_USER_FSC";
	String P_I_USER_PERM="P_I_USER_PERM";
	String P_I_POD_TERM="P_I_POD_TERM";
	String P_I_COCSOC="P_I_COCSOC";
	String P_I_FILTER="P_I_FILTER";
	String P_I_RATE_REF="P_I_RATE_REF";
	String P_I_SLOT_PARTNER="P_I_SLOT_PARTNER";
	String P_I_CUSTOMER="P_I_CUSTOMER";
	String P_I_PORT_TARIFF="P_I_PORT_TARIFF";
	String P_I_POL_TERM="P_I_POL_TERM";
	String P_I_S="P_I_S";
	String P_I_IPV_STATUS="P_I_IPV_STATUS";
	String P_I_IMP_EXP="P_I_IMP_EXP";
	String P_I_OPERATOR_TYPE="P_I_OPERATOR_TYPE";
	String P_I_ATD_TO="P_I_ATD_TO";
	String P_I_ATD_FROM="P_I_ATD_FROM";
	String P_I_PORT_TERM="P_I_PORT_TERM";
	String P_I_ETA_FROM="P_I_ETA_FROM";
	String P_I_ETA_TO="P_I_ETA_TO";
	String P_I_PROF_REF_NO="P_I_PROF_REF_NO";
	String P_I_COMM_TYPE="P_I_COMM_TYPE";
	String P_I_FROM_YEAR="P_I_FROM_YEAR";                   
	String P_I_FROM_MONTH="P_I_FROM_MONTH";                    
	String P_I_TO_YEAR="P_I_TO_YEAR";                 
	String P_I_TO_MONTH="P_I_TO_MONTH";   
	String P_I_MON_REIM="P_I_MON_REIM";                           
	String P_I_INVOICE_STATUS="P_I_INVOICE_STATUS";                        
	String P_I_INVOICE_NO="P_I_INVOICE_NO";                 
	String P_I_COM_FRT_TAX="P_I_COM_FRT_TAX";
	  
}
